version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  test-runner:
    build: .
    depends_on:
      - selenium
    volumes:
      - ./screenshots:/app/screenshots